### ISSUE TITLE
dynamodb:GetItem fails using AsyncioBotocore when response uses gzip compression

### ISSUE THREAD

**Issue by adamrothman** [quantmind/pulsar-cloud#15]
A simple GetItem call fails with the following traceback:

```python
Traceback (most recent call last):
  File "./ddbench.py", line 571, in <module>
    loop.run_until_complete(main(args.n))
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "./ddbench.py", line 562, in main
    await time_pulsar(n, kwargses)
  File "./ddbench.py", line 541, in time_pulsar
    result = await client.get_item(**kwargs)
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cloud/asyncbotocore/client.py", line 73, in _make_api_call
    operation_model, request_dict)
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cloud/asyncbotocore/endpoint.py", line 69, in _send_request
    success_response, exception):
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cloud/asyncbotocore/endpoint.py", line 138, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/site-packages/botocore/retryhandler.py", line 220, in __call__
    return self._check_response(attempt_number, response)
  File "/Users/adam/.pyenv/versions/3.5.2/lib/python3.5/site-packages/botocore/retryhandler.py", line 342, in _check_response
    actual_checksum=actual_crc32)
botocore.exceptions.ChecksumError: Checksum crc32 failed, expected checksum 1594468658 did not match calculated checksum 405083545.
```

I did a bit of digging and this appears to be the same problem that was solved in aiobotocore with this patch: https://github.com/aio-libs/aiobotocore/commit/9cd8ea3e136b4c64269e1f1ef15a4876c10adf61

**Comment by lsbardel** [comment]
Thanks, we need dynamodb tests for this :scream:

**Comment by lsbardel** [comment]
I've added a `dynamodb` test file with a simple test which passes in the `dev` branch.
https://github.com/quantmind/pulsar-cloud/blob/dev/tests/test_dynamodb.py
Do you think you could add one where I can see the failure you are reporting?
Many thanks

**Comment by adamrothman** [comment]
From the commit message for aio-libs/aiobotocore@9cd8ea3:

> When using aiobotocore with dynamodb, requests fail on crc32 checksum computation as soon as the response data reaches ~5KB.
> 
> It seems that this is  due to aws sending data back in gzip compressed format, aiohttp automatically uncompressing it and crc32 checksum being computed on the uncompressed data bytes. While crc32 has to be computed on compressed data in order to pass.
> 
> The same requests work as expected when using botocore, this commit forces aws not to use gzip compression.

I can't write up a test case at the moment but any operation that triggers a response larger than 5KB should do it.

**Comment by lsbardel** [comment]
This is fixed, in a much better way.
Pass `decompress=False` when creating the pulsar Http client and perform decompression in `convert_to_response_dict`

**Comment by adamrothman** [comment]
@lsbardel Awesome, thank you!
